server:
  port: 8084
bin:
  api:
    url: https://api.binlist.net

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/cardscheme?useUnicode=true&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
   
    hibernate:
      ddl-auto: update
      

 